#!/usr/bin/env bash
set -Eeuo pipefail

: "${FLY_API_APP:?Set FLY_API_APP}"
: "${FLY_WEB_APP:?Set FLY_WEB_APP}"
: "${FLY_REGION:?Set FLY_REGION}"
: "${NEXT_PUBLIC_API_URL:?Set NEXT_PUBLIC_API_URL}"
: "${NEXT_PUBLIC_SITE_URL:?Set NEXT_PUBLIC_SITE_URL}"
: "${NEXT_PUBLIC_SITE_EMAIL:?Set NEXT_PUBLIC_SITE_EMAIL}"
: "${NEXT_PUBLIC_SITE_LOCATION:?Set NEXT_PUBLIC_SITE_LOCATION}"
: "${FRONTEND_ORIGINS:?Set FRONTEND_ORIGINS}"
: "${PUBLIC_SITE_URL:?Set PUBLIC_SITE_URL}"
: "${PUBLIC_SITE_EMAIL:?Set PUBLIC_SITE_EMAIL}"
: "${PUBLIC_SITE_LOCATION:?Set PUBLIC_SITE_LOCATION}"
: "${DATABASE_URL:?Set DATABASE_URL}"
: "${SMTP_HOST:?Set SMTP_HOST}"
: "${SMTP_PORT:?Set SMTP_PORT}"
: "${SMTP_USER:?Set SMTP_USER}"
: "${SMTP_PASSWORD:?Set SMTP_PASSWORD}"
: "${SMTP_FROM:?Set SMTP_FROM}"
: "${SMTP_SECURE:?Set SMTP_SECURE}"
: "${SMTP_REQUIRE_TLS:?Set SMTP_REQUIRE_TLS}"
: "${ADMIN_EMAIL:?Set ADMIN_EMAIL}"
: "${ADMIN_NAME:?Set ADMIN_NAME}"
: "${ADMIN_PASSWORD:?Set ADMIN_PASSWORD}"
STORAGE_PROVIDER="${STORAGE_PROVIDER:-local}"
if [[ "$STORAGE_PROVIDER" == s3 ]]; then
  : "${STORAGE_BUCKET:?Set STORAGE_BUCKET when STORAGE_PROVIDER=s3}"
  : "${STORAGE_ACCESS_KEY_ID:?Set STORAGE_ACCESS_KEY_ID when STORAGE_PROVIDER=s3}"
  : "${STORAGE_SECRET_ACCESS_KEY:?Set STORAGE_SECRET_ACCESS_KEY when STORAGE_PROVIDER=s3}"
fi

fly secrets set --app "$FLY_API_APP" \
  DATABASE_URL="$DATABASE_URL" FRONTEND_ORIGINS="$FRONTEND_ORIGINS" \
  PUBLIC_SITE_URL="$PUBLIC_SITE_URL" PUBLIC_SITE_EMAIL="$PUBLIC_SITE_EMAIL" \
  PUBLIC_SITE_LOCATION="$PUBLIC_SITE_LOCATION" \
  SMTP_HOST="$SMTP_HOST" SMTP_PORT="$SMTP_PORT" \
  SMTP_USER="$SMTP_USER" SMTP_PASSWORD="$SMTP_PASSWORD" \
  SMTP_FROM="$SMTP_FROM" SMTP_SECURE="$SMTP_SECURE" \
  SMTP_REQUIRE_TLS="$SMTP_REQUIRE_TLS" \
  STORAGE_PROVIDER="$STORAGE_PROVIDER" \
  STORAGE_BUCKET="${STORAGE_BUCKET:-}" \
  STORAGE_ENDPOINT="${STORAGE_ENDPOINT:-}" \
  STORAGE_REGION="${STORAGE_REGION:-auto}" \
  STORAGE_ACCESS_KEY_ID="${STORAGE_ACCESS_KEY_ID:-}" \
  STORAGE_SECRET_ACCESS_KEY="${STORAGE_SECRET_ACCESS_KEY:-}" \
  STORAGE_FORCE_PATH_STYLE="${STORAGE_FORCE_PATH_STYLE:-false}" \
  ADMIN_EMAIL="$ADMIN_EMAIL" ADMIN_NAME="$ADMIN_NAME" \
  ADMIN_PASSWORD="$ADMIN_PASSWORD"

fly deploy --config fly.api.toml --app "$FLY_API_APP"
fly deploy --config fly.web.toml --app "$FLY_WEB_APP" \
  --build-arg NEXT_PUBLIC_API_URL="$NEXT_PUBLIC_API_URL" \
  --build-arg NEXT_PUBLIC_SITE_URL="$NEXT_PUBLIC_SITE_URL" \
  --build-arg NEXT_PUBLIC_SITE_EMAIL="$NEXT_PUBLIC_SITE_EMAIL" \
  --build-arg NEXT_PUBLIC_SITE_LOCATION="$NEXT_PUBLIC_SITE_LOCATION"
