#!/usr/bin/env bash
set -Eeuo pipefail

: "${FLY_API_APP:?Set FLY_API_APP}"
: "${FLY_WEB_APP:?Set FLY_WEB_APP}"
: "${FLY_REGION:?Set FLY_REGION}"
: "${NEXT_PUBLIC_API_URL:?Set NEXT_PUBLIC_API_URL}"
: "${FRONTEND_ORIGINS:?Set FRONTEND_ORIGINS}"
: "${DATABASE_URL:?Set DATABASE_URL}"
: "${SMTP_HOST:?Set SMTP_HOST}"
: "${SMTP_PORT:?Set SMTP_PORT}"
: "${SMTP_USER:?Set SMTP_USER}"
: "${SMTP_PASSWORD:?Set SMTP_PASSWORD}"
: "${SMTP_FROM:?Set SMTP_FROM}"
: "${SMTP_SECURE:?Set SMTP_SECURE}"
: "${SMTP_REQUIRE_TLS:?Set SMTP_REQUIRE_TLS}"
: "${ADMIN_EMAIL:?Set ADMIN_EMAIL}"
: "${ADMIN_NAME:?Set ADMIN_NAME}"
: "${ADMIN_PASSWORD:?Set ADMIN_PASSWORD}"

fly secrets set --app "$FLY_API_APP" \
  DATABASE_URL="$DATABASE_URL" FRONTEND_ORIGINS="$FRONTEND_ORIGINS" \
  SMTP_HOST="$SMTP_HOST" SMTP_PORT="$SMTP_PORT" \
  SMTP_USER="$SMTP_USER" SMTP_PASSWORD="$SMTP_PASSWORD" \
  SMTP_FROM="$SMTP_FROM" SMTP_SECURE="$SMTP_SECURE" \
  SMTP_REQUIRE_TLS="$SMTP_REQUIRE_TLS" \
  ADMIN_EMAIL="$ADMIN_EMAIL" ADMIN_NAME="$ADMIN_NAME" \
  ADMIN_PASSWORD="$ADMIN_PASSWORD"

fly deploy --config fly.api.toml --app "$FLY_API_APP"
fly deploy --config fly.web.toml --app "$FLY_WEB_APP" \
  --build-arg NEXT_PUBLIC_API_URL="$NEXT_PUBLIC_API_URL"
